serenity {
    project.name = "Appium Mobile Testing — FlowersApp"
    report {
        directory = "target/site/serenity"
    }
}

drivers {
    appium {
        appiumServerPath = "http://127.0.0.1:4723"
    }
}
